# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.provider "parallels" do |prl|
    prl.update_guest_tools = true
    prl.name = "Vagrant IIQ Vanilla"
    prl.customize ["set", :id, "--device-set", "cdrom0", "--image", "/Applications/Parallels Desktop.app/Contents/Resources/Tools/prl-tools-lin-arm.iso", "--connect"]
  end

  config.vm.box = "debian-arm"

  config.vm.network "forwarded_port", guest: 8080, host: 8181, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 80, host: 8888, host_ip: "127.0.0.1"

  config.vm.network "private_network", ip: "192.168.56.10"

  config.ssh.dsa_authentication = false
  config.ssh.username = "sailpoint"
  config.ssh.password = "Sailp0!nt"
  #config.ssh.host = '192.168.56.10'

  config.vm.synced_folder "../ansible", "/tmp/vagrant"

  config.vm.provision "ansible_local" do |ansible|
    ansible.become = true
    ansible.become_user = "root"
    ansible.playbook = "/tmp/vagrant/playbook.yml"
    ansible.galaxy_role_file = "/tmp/vagrant/roles/requirements.yml"
    ansible.galaxy_command = "ansible-galaxy  collection install -r /tmp/vagrant/roles/requirements.yml && ansible-galaxy install -r /tmp/vagrant/roles/requirements.yml"
    ansible.compatibility_mode = "2.0"
    ansible.vault_password_file = "/tmp/vagrant/vault-password-file"
    # To force java 11. The version is calculated in vars/main.yml which has a very high precedence
    ansible.extra_vars = {
  java_version: 11,
  java_default_version: 11
}

  end
end
